### ISSUE TITLE
Adding the medical news headlins to the application

### ISSUE THREAD

**Issue by rshrc** [allisto/allisto-app#7]
Using the https://newsapi.org/ to fetch and display news in a list form in the news_page section of the application.

**Comment by yashovardhan99** [comment]
Can we make this and #8 into a project (planning for v1).

**Comment by yashovardhan99** [comment]
@rshrc This is done in #14 right?

**Comment by rshrc** [comment]
@yashovardhan99 yes it is done, let me close this issue
